# Terms of Service

**Effective Date:** August 21, 2026

## 1. Acceptance of Terms

By inviting, accessing, or using PUBG Tracker (“the Bot”), you agree to these Terms of Service. If you do not agree, remove the Bot from your Discord server and discontinue use.

## 2. Description of Service

PUBG Tracker is a Discord utility bot for PUBG communities and clans. Features may include:

- Tracking PUBG player statistics and match activity.
- Displaying lifetime, ranked, leaderboard, clan, weapon, and survival information obtained from the official PUBG API.
- Creating server-specific reports, including scheduled daily or weekly reports.
- Allowing authorized server members to configure tracked players, reporting channels, scheduled times, clan settings, and ranked queues.

Features may change as the Bot is updated.

## 3. Public Game Data

The Bot retrieves PUBG-related information through the official PUBG API. Reported game statistics, player names, rankings, match information, and clan information depend on what PUBG makes available through its API.

The Bot does not guarantee that PUBG data is complete, current, accurate, or available for every player, platform, game mode, or region.

## 4. Server Administration and Configuration

Server administrators are responsible for:

- Ensuring they have permission to add the Bot to their server.
- Configuring reporting channels and schedules appropriately.
- Managing the server’s tracked-player list.
- Ensuring their members understand that requested reports may display public PUBG player names and statistics in Discord channels.

The Bot may use Discord webhooks to format player-specific report messages. These messages are generated by the Bot and do not change a Discord member’s actual account name or profile.

## 5. Fair Use and API Limits

PUBG Tracker relies on third-party services, including Discord and the official PUBG API. Requests may be delayed, limited, cached, retried, or unavailable because of API rate limits, outages, maintenance, or service changes.

Large reports, particularly first-time ranked roster scans, can take several minutes. The Bot is not responsible for delays or unavailable data caused by third-party limits.

## 6. User Conduct

You agree not to:

- Use the Bot for unlawful, harmful, abusive, or fraudulent purposes.
- Violate Discord’s Terms of Service, Community Guidelines, or applicable laws.
- Attempt to reverse engineer, exploit, overload, disrupt, or interfere with the Bot, its host, Discord, or the PUBG API.
- Use the Bot to harass, impersonate, threaten, or target other users.
- Attempt to access Bot data, credentials, or server configurations without authorization.

## 7. Availability and Changes

The Bot is provided on an “AS IS” and “AS AVAILABLE” basis. We may modify, limit, suspend, or discontinue the Bot or any feature at any time, with or without notice.

We do not guarantee uninterrupted availability, compatibility with every Discord server, or continued access to any third-party API feature.

## 8. Disclaimer of Warranties

To the maximum extent permitted by law, the Bot is provided without warranties of any kind, whether express, implied, or statutory. This includes warranties of accuracy, reliability, fitness for a particular purpose, non-infringement, and uninterrupted service.

## 9. Limitation of Liability

To the maximum extent permitted by applicable law, the Bot’s creator and maintainers are not liable for any indirect, incidental, special, consequential, exemplary, or punitive damages arising from use of, inability to use, or reliance on the Bot or its reports.

This includes loss of data, lost server activity, inaccurate game statistics, delayed reports, service interruption, or third-party API failures.

## 10. Privacy

Use of the Bot is also governed by the PUBG Tracker Privacy Policy. By using the Bot, you acknowledge that it may process Discord server configuration data and public PUBG-related data as described in that policy.

## 11. Changes to These Terms

These Terms may be updated as the Bot changes or legal requirements evolve. Continued use of the Bot after an updated effective date means you accept the revised Terms.

## 12. Contact

For questions or concerns about these Terms, contact the Bot’s developer or use the community support channels associated with PUBG Tracker.
